import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { format, resolveConfig } from "prettier";

function parseCsv(csv: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let quoted = false;

  // Quoted fields may contain commas, newlines, and escaped double quotes.
  csv = csv.replace(/^\uFEFF/, "");
  for (let index = 0; index < csv.length; index++) {
    const character = csv[index];
    if (character === '"') {
      if (quoted && csv[index + 1] === '"') {
        field += '"';
        index++;
      } else {
        quoted = !quoted;
      }
    } else if (!quoted && character === ",") {
      row.push(field);
      field = "";
    } else if (!quoted && (character === "\n" || character === "\r")) {
      row.push(field);
      if (row.some((value) => value !== "")) rows.push(row);
      row = [];
      field = "";
      if (character === "\r" && csv[index + 1] === "\n") index++;
    } else {
      field += character;
    }
  }

  if (quoted) throw new Error("Unterminated quoted CSV field.");
  if (row.length > 0 || field !== "") {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

function readCompletion(csv: string): Map<string, string> {
  const rows = parseCsv(csv);
  const keyIndex = rows[0]?.indexOf("key") ?? -1;
  // Column "43" is Text, the fifth CSV field after the row key.
  const textIndex = rows[0]?.indexOf("43") ?? -1;
  if (keyIndex < 0 || textIndex < 0) {
    throw new Error('Completion.csv must contain columns "key" and "43".');
  }

  const texts = new Map<string, string>();
  // Skip column numbers, column names, offsets, and types.
  for (const row of rows.slice(4)) {
    const key = row[keyIndex];
    const text = row[textIndex];
    if (key === undefined || text === undefined) {
      throw new Error("Incomplete Completion.csv row.");
    }
    texts.set(key, text);
  }
  return texts;
}

export function buildDict(
  englishCsv: string,
  chineseCsv: string,
): Record<string, string> {
  const englishTexts = readCompletion(englishCsv);
  const chineseTexts = readCompletion(chineseCsv);
  const entries: [string, string][] = [];

  for (const [key, english] of englishTexts) {
    const chinese = chineseTexts.get(key);
    if (!english || !chinese) continue;
    entries.push([english.toLowerCase(), chinese]);
  }

  // Duplicate English text keeps the last nonempty Chinese translation.
  return Object.fromEntries(entries);
}

if (import.meta.main) {
  const [englishCsv, chineseCsv] = await Promise.all([
    readFile(
      new URL("../ffxiv-data/en/ContentFinderCondition.csv", import.meta.url),
      "utf8",
    ),
    readFile(
      new URL("../ffxiv-data/chs/ContentFinderCondition.csv", import.meta.url),
      "utf8",
    ),
  ]);
  const dict = buildDict(englishCsv, chineseCsv);
  const output = new URL("../src/constants/dict-zh-cn.ts", import.meta.url);
  const source = `// Generated by scripts/build-dict.ts. Do not edit manually.
export const DICT: Readonly<Record<string, string>> = ${JSON.stringify(dict, null, 2)};

export default DICT;
`.replace(/<hex:021A020203>|<hex:021A020103>/g, "");

  const formatted = await format(source, {
    ...(await resolveConfig(fileURLToPath(output))),
    parser: "typescript",
  });
  await mkdir(new URL("../src/constants/", import.meta.url), {
    recursive: true,
  });
  await writeFile(output, formatted, "utf8");
  console.log(
    `Generated ${Object.keys(dict).length} mappings in ${fileURLToPath(output)}.`,
  );
}
