import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { format, resolveConfig } from "prettier";

export interface DictSourceConfig {
  fileName: string;
  column: string;
  // Filters receive the lowercase English dictionary key.
  filter?: (key: string) => boolean;
}

export interface DictSource extends DictSourceConfig {
  englishCsv: string;
  chineseCsv: string;
}

// Add CSV sources here; later sources override earlier mappings.
const SOURCES: readonly DictSourceConfig[] = [
  { fileName: "ContentFinderCondition.csv", column: "43" },
  { fileName: "ContentType.csv", column: "0" },
  {
    fileName: "EventItem.csv",
    column: "0",
    filter: (key) =>
      key.endsWith("treasure map") || key.endsWith("thief's map"),
  },
];

function parseCsv(csv: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let quoted = false;

  // Quoted fields may contain commas, newlines, and escaped double quotes.
  csv = csv.replace(/^\uFEFF/, "");
  for (let index = 0; index < csv.length; index++) {
    const character = csv[index];
    if (character === '"') {
      if (quoted && csv[index + 1] === '"') {
        field += '"';
        index++;
      } else {
        quoted = !quoted;
      }
    } else if (!quoted && character === ",") {
      row.push(field);
      field = "";
    } else if (!quoted && (character === "\n" || character === "\r")) {
      row.push(field);
      if (row.some((value) => value !== "")) rows.push(row);
      row = [];
      field = "";
      if (character === "\r" && csv[index + 1] === "\n") index++;
    } else {
      field += character;
    }
  }

  if (quoted) throw new Error("Unterminated quoted CSV field.");
  if (row.length > 0 || field !== "") {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

function readTexts(
  csv: string,
  column: string,
  fileName: string,
): Map<string, string> {
  const rows = parseCsv(csv);
  const keyIndex = rows[0]?.indexOf("key") ?? -1;
  const textIndex = rows[0]?.indexOf(column) ?? -1;
  if (keyIndex < 0 || textIndex < 0) {
    throw new Error(`${fileName} must contain columns "key" and "${column}".`);
  }

  const texts = new Map<string, string>();
  // Skip column numbers, column names, offsets, and types.
  for (const row of rows.slice(4)) {
    const key = row[keyIndex];
    const text = row[textIndex];
    if (key === undefined || text === undefined) {
      throw new Error(`Incomplete ${fileName} row.`);
    }
    texts.set(key, text);
  }
  return texts;
}

export function buildDict(
  sources: readonly DictSource[],
): Record<string, string> {
  const entries: [string, string][] = [];

  for (const { fileName, column, englishCsv, chineseCsv, filter } of sources) {
    const englishTexts = readTexts(englishCsv, column, fileName);
    const chineseTexts = readTexts(chineseCsv, column, fileName);

    for (const [key, english] of englishTexts) {
      const chinese = chineseTexts.get(key);
      if (!english || !chinese) continue;
      const name = english.toLowerCase();
      if (filter && !filter(name)) continue;
      entries.push([name, chinese]);
    }
  }

  // Duplicate English text keeps the last nonempty Chinese translation.
  return Object.fromEntries(entries);
}

if (import.meta.main) {
  const sources = await Promise.all(
    SOURCES.map(async (source) => {
      const [englishCsv, chineseCsv] = await Promise.all([
        readFile(
          new URL(`../ffxiv-data/en/${source.fileName}`, import.meta.url),
          "utf8",
        ),
        readFile(
          new URL(`../ffxiv-data/chs/${source.fileName}`, import.meta.url),
          "utf8",
        ),
      ]);
      return { ...source, englishCsv, chineseCsv };
    }),
  );
  const dict = buildDict(sources);
  const output = new URL("../src/constants/dict-zh-cn.ts", import.meta.url);
  const source = `// Generated by scripts/build-dict.ts. Do not edit manually.
export const DICT: Readonly<Record<string, string>> = ${JSON.stringify(dict, null, 2)};

export default DICT;
`.replace(/<hex:021A020203>|<hex:021A020103>/g, "");

  const formatted = await format(source, {
    ...(await resolveConfig(fileURLToPath(output))),
    parser: "typescript",
  });
  await mkdir(new URL("../src/constants/", import.meta.url), {
    recursive: true,
  });
  await writeFile(output, formatted, "utf8");
  console.log(
    `Generated ${Object.keys(dict).length} mappings in ${fileURLToPath(output)}.`,
  );
}
